# Generated by Django 5.1 on 2024-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('live_img', models.FileField(blank=True, null=True, upload_to='live_img/')),
                ('live_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
