# Generated by Django 5.1 on 2024-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevideo',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='livevideo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
